import React, { useCallback, useEffect, useState, useMemo, useRef } from 'react';
import { MdImageSearch } from 'react-icons/md';
import { FaBroom } from 'react-icons/fa';
import { HiOutlinePlus } from 'react-icons/hi';
import { HiOutlineRefresh as RefreshIcon } from 'react-icons/hi';
import { IoIosFolderOpen, IoIosUndo } from 'react-icons/io';
import { VscTerminal } from 'react-icons/vsc';
import cx from 'classnames';
import {
  type AssetPack,
  fetchLatestCatalog,
  getCatalogSource,
  isSmart,
} from '../../lib/logic/catalog';
import { getConfig } from '../../lib/logic/config';
import { getSceneClient } from '../../lib/rpc/scene';
import { useSnackbar } from '../../hooks/useSnackbar';
import {
  clearRemovedFiles,
  selectRemovedFiles,
  selectHasRecoverableFiles,
} from '../../redux/clean-assets';
import { useAppDispatch, useAppSelector } from '../../redux/hooks';
import {
  selectAssetToRename,
  selectStagedCustomAsset,
  getAssetCatalog,
  getDataLayerInterface,
} from '../../redux/data-layer';
import {
  getSelectedAssetsTab,
  selectAssetsTab,
  getDebugConsoleEnabled,
  getMobileDebugSessionEnabled,
} from '../../redux/ui';
import { AssetsTab } from '../../redux/ui/types';
import { useScanAssets } from '../../hooks/useScanAssets';
import { useImportAssetToFilesystem } from '../../hooks/useImportAssetToFilesystem';
import { FolderOpen } from '../Icons/Folder';
import CleanupIcon from '../Icons/Cleanup';
import { AssetsCatalog } from '../AssetsCatalog';
import { CatalogAssetContextMenu } from '../AssetsCatalog/Asset/ContextMenu/CatalogAssetContextMenu';
import { ProjectAssetExplorer } from '../ProjectAssetExplorer';
import ImportAsset from '../ImportAsset';
import { CustomAssets } from '../CustomAssets';
import { RenameAsset } from '../RenameAsset';
import { CreateCustomAsset } from '../CreateCustomAsset';
import { CleanAssets } from '../CleanAssets';
import type { InputRef } from '../FileInput/FileInput';
import { Button } from '../Button';
import { InfoTooltip } from '../ui';
import DebugConsole from './DebugConsole';
import MobileDebugSession from './MobileDebugSession/MobileDebugSession';

import './Assets.css';

function removeSmartItems(assetPack: AssetPack) {
  return {
    ...assetPack,
    assets: assetPack.assets.filter(asset => !isSmart(asset)),
  };
}

function Assets({ isAssetsPanelCollapsed }: { isAssetsPanelCollapsed: boolean }) {
  const dispatch = useAppDispatch();
  const tab = useAppSelector(getSelectedAssetsTab);
  const removedAssets = useAppSelector(selectRemovedFiles);
  const hasRecoverableFiles = useAppSelector(selectHasRecoverableFiles);
  const debugConsoleEnabled = useAppSelector(getDebugConsoleEnabled);
  const mobileDebugSessionEnabled = useAppSelector(getMobileDebugSessionEnabled);
  const [showCleanAssetsModal, setShowCleanAssetsModal] = useState(false);
  const [selectedCleanAssets, setSelectedCleanAssets] = useState<Set<string>>(new Set());
  const { pushNotification } = useSnackbar();

  const inputRef = useRef<InputRef>(null);
  const { importCatalogAssetToFilesystem, importCustomAssetToFilesystem } =
    useImportAssetToFilesystem();

  const {
    assets: cleanAssets,
    isScanning,
    scanAssets,
  } = useScanAssets([
    'main.composite',
    'assets/composite.json',
    'assets/images/autogenerated-thumbnail.png',
  ]);

  useEffect(() => {
    if (debugConsoleEnabled) {
      dispatch(selectAssetsTab({ tab: AssetsTab.DebugConsole }));
    } else if (tab === AssetsTab.DebugConsole) {
      dispatch(selectAssetsTab({ tab: AssetsTab.AssetsPack }));
    }
  }, [debugConsoleEnabled]);

  const handleTabClick = useCallback(
    (tab: AssetsTab) => () => {
      dispatch(selectAssetsTab({ tab }));
    },
    [],
  );

  const config = getConfig();
  const [catalog, setCatalog] = useState<AssetPack[]>([]);
  const [catalogUnavailable, setCatalogUnavailable] = useState(false);

  useEffect(() => {
    fetchLatestCatalog()
      .then(packs => {
        setCatalog(packs);
        setCatalogUnavailable(getCatalogSource() === 'bundled');
      })
      .catch(err => {
        console.error('Failed to load asset catalog:', err);
        void pushNotification(
          'error',
          'Could not load the asset catalog. Please check your connection and try again.',
        );
      });
  }, []);

  const filteredCatalog = config.disableSmartItems
    ? catalog.map(removeSmartItems).filter(assetPack => assetPack.assets.length > 0)
    : catalog;

  const assetToRename = useAppSelector(selectAssetToRename);
  const stagedCustomAsset = useAppSelector(selectStagedCustomAsset);

  const handleImportClick = useCallback(() => {
    inputRef.current?.onClick();
  }, [inputRef]);

  const handleRefreshClick = useCallback(() => {
    dispatch(getAssetCatalog());
  }, [dispatch]);

  const handleScanAssets = useCallback(async () => {
    const assets = await scanAssets();
    const selectedAssets = new Set<string>(
      assets.filter(asset => asset.unused).map(asset => asset.path),
    );
    setSelectedCleanAssets(selectedAssets);
  }, [scanAssets]);

  const handleCleanAssetsClick = useCallback(async () => {
    setShowCleanAssetsModal(true);
    handleScanAssets();
  }, [handleScanAssets]);

  const handleCloseCleanAssetsModal = useCallback(() => {
    setSelectedCleanAssets(new Set());
    setShowCleanAssetsModal(false);
  }, []);

  const handleSelectCleanAsset = useCallback((value: string) => {
    setSelectedCleanAssets(prevSet => {
      const isSelected = prevSet.has(value);
      const newSet = new Set(prevSet);
      if (isSelected) newSet.delete(value);
      else newSet.add(value);
      return newSet;
    });
  }, []);

  const handleSelectAllCleanAssets = useCallback(
    (selectAll: boolean) => {
      if (selectAll) {
        setSelectedCleanAssets(new Set(cleanAssets.map(asset => asset.path)));
      } else {
        setSelectedCleanAssets(new Set());
      }
    },
    [cleanAssets],
  );

  const handleOpenInExplorer = useCallback(async () => {
    try {
      const sceneClient = getSceneClient();
      if (!sceneClient) return;

      const path = tab === AssetsTab.CustomAssets ? 'custom' : '.';
      await sceneClient.openDirectory(path, tab === AssetsTab.CustomAssets);
    } catch (error) {
      console.error('Failed to open folder:', error);
    }
  }, [tab]);

  const handleOptimizeClick = useCallback(() => {
    // The optimizer runs in the Creator Hub main process (it needs the native
    // texture toolchain); the inspector only asks the host to open its modal.
    // A host that does not implement the method (the standalone inspector) rejects, which is
    // nothing to surface — but leaving it floating makes it an unhandled rejection.
    void getSceneClient()
      ?.optimizeScene()
      .catch(error => console.warn('The host does not support optimize_scene:', error));
  }, []);

  const handleRecoverAssets = useCallback(async () => {
    if (removedAssets.length === 0) return;

    const dataLayer = getDataLayerInterface();
    if (!dataLayer) return;

    let successCount = 0;
    for (const file of removedAssets) {
      try {
        await dataLayer.saveFile({ path: file.path, content: file.content });
        successCount++;
      } catch (error) {
        console.error(`Failed to recover ${file.path}:`, error);
      }
    }

    if (successCount > 0) {
      pushNotification(
        'success',
        `${successCount} ${successCount === 1 ? 'file has' : 'files have'} been successfully recovered.`,
      );
      dispatch(getAssetCatalog());
    }

    dispatch(clearRemovedFiles());
  }, [removedAssets, dispatch, pushNotification]);

  const showCleanAssetsButton = useMemo(() => tab === AssetsTab.FileSystem, [tab]);
  // Only inside the Creator Hub (host bridge present) — the optimizer runs in CH main.
  const showOptimizeButton = useMemo(
    () => tab === AssetsTab.FileSystem && !!config.dataLayerRpcParentUrl,
    [tab, config.dataLayerRpcParentUrl],
  );
  const showRecoverAssetsButton = useMemo(
    () => tab === AssetsTab.FileSystem && hasRecoverableFiles,
    [tab, hasRecoverableFiles],
  );
  const showOpenInExplorerButton = useMemo(() => {
    return (
      config.dataLayerRpcParentUrl &&
      (tab === AssetsTab.FileSystem || tab === AssetsTab.CustomAssets)
    );
  }, [tab, config.dataLayerRpcParentUrl]);
  const openInExplorerTooltipText = useMemo(() => {
    const text = tab === AssetsTab.CustomAssets ? 'custom items' : 'scene';
    return `Open ${text} folder in Explorer`;
  }, [tab]);

  return (
    <div className="Assets">
      <div className="Assets-buttons">
        {tab !== AssetsTab.DebugConsole && (
          <div className="Assets-buttons-left">
            <Button
              className="import-button"
              onClick={handleImportClick}
            >
              <HiOutlinePlus />
              IMPORT ASSETS
            </Button>
            <InfoTooltip
              text="Refresh assets"
              trigger={
                <RefreshIcon
                  className="icon-item"
                  onClick={handleRefreshClick}
                />
              }
              openOnTriggerMouseEnter={true}
              closeOnTriggerClick={true}
              position="top center"
            />
            {showOpenInExplorerButton && (
              <InfoTooltip
                text={openInExplorerTooltipText}
                trigger={
                  <IoIosFolderOpen
                    className="icon-item"
                    onClick={handleOpenInExplorer}
                  />
                }
                openOnTriggerMouseEnter={true}
                closeOnTriggerClick={true}
                position="top center"
              />
            )}
            {showCleanAssetsButton && (
              <InfoTooltip
                text="Clean unused assets"
                trigger={
                  <button
                    className="icon-item"
                    onClick={handleCleanAssetsClick}
                  >
                    <CleanupIcon />
                  </button>
                }
                openOnTriggerMouseEnter={true}
                closeOnTriggerClick={true}
                position="top center"
              />
            )}
            {showOptimizeButton && (
              <InfoTooltip
                text="Optimize models"
                trigger={
                  <button
                    className="icon-item"
                    onClick={handleOptimizeClick}
                  >
                    <FaBroom />
                  </button>
                }
                openOnTriggerMouseEnter={true}
                closeOnTriggerClick={true}
                position="top center"
              />
            )}
            {showRecoverAssetsButton && (
              <InfoTooltip
                text="Recover assets removed"
                trigger={
                  <IoIosUndo
                    className="icon-item"
                    onClick={handleRecoverAssets}
                  />
                }
                openOnTriggerMouseEnter={true}
                closeOnTriggerClick={true}
                position="top center"
              />
            )}
          </div>
        )}
        <div
          className="tab"
          onClick={handleTabClick(AssetsTab.FileSystem)}
          data-test-id={AssetsTab.FileSystem}
        >
          <div className={cx({ underlined: tab === AssetsTab.FileSystem })}>
            <FolderOpen />
            <span>LOCAL ASSETS</span>
          </div>
        </div>
        <div
          className="tab"
          onClick={handleTabClick(AssetsTab.CustomAssets)}
          data-test-id={AssetsTab.CustomAssets}
        >
          <div className={cx({ underlined: tab === AssetsTab.CustomAssets })}>
            <i className="icon-custom-assets" />
            <span>CUSTOM ITEMS</span>
          </div>
        </div>
        <div
          className="tab"
          onClick={handleTabClick(AssetsTab.AssetsPack)}
          data-test-id={AssetsTab.AssetsPack}
        >
          <div className={cx({ underlined: tab === AssetsTab.AssetsPack })}>
            <MdImageSearch />
            <span>ASSET PACKS</span>
          </div>
        </div>
        {debugConsoleEnabled && (
          <div
            className="tab"
            onClick={handleTabClick(AssetsTab.DebugConsole)}
            data-test-id={AssetsTab.DebugConsole}
          >
            <div className={cx({ underlined: tab === AssetsTab.DebugConsole })}>
              <VscTerminal />
              <span>CONSOLE</span>
            </div>
          </div>
        )}
        {mobileDebugSessionEnabled && (
          <div
            className="tab"
            onClick={handleTabClick(AssetsTab.MobileDebugSession)}
            data-test-id={AssetsTab.MobileDebugSession}
          >
            <div className={cx({ underlined: tab === AssetsTab.MobileDebugSession })}>
              <VscTerminal />
              <span>MOBILE DEBUG SESSION</span>
            </div>
          </div>
        )}
      </div>
      {tab === AssetsTab.MobileDebugSession ? (
        <div className={cx('Assets-content', { Hide: isAssetsPanelCollapsed })}>
          <MobileDebugSession />
        </div>
      ) : tab === AssetsTab.DebugConsole ? (
        <div className={cx('Assets-content', { Hide: isAssetsPanelCollapsed })}>
          <DebugConsole />
        </div>
      ) : (
        <ImportAsset
          onSave={handleTabClick(AssetsTab.FileSystem)}
          ref={inputRef}
        >
          <div className={cx('Assets-content', { Hide: isAssetsPanelCollapsed })}>
            {tab === AssetsTab.AssetsPack &&
              (catalogUnavailable ? (
                <div className="AssetsCatalogUnavailable">
                  <p>Asset Packs are unavailable.</p>
                  <p>
                    The content server could not be reached. Check your connection and try again.
                  </p>
                </div>
              ) : (
                <AssetsCatalog
                  catalog={filteredCatalog}
                  onAddToFilesystem={importCatalogAssetToFilesystem}
                />
              ))}
            {tab === AssetsTab.FileSystem && <ProjectAssetExplorer />}
            {tab === AssetsTab.CustomAssets && (
              <CustomAssets onAddToFilesystem={importCustomAssetToFilesystem} />
            )}
            {tab === AssetsTab.RenameAsset && assetToRename && (
              <RenameAsset
                assetId={assetToRename.id}
                currentName={assetToRename.name}
              />
            )}
            {tab === AssetsTab.CreateCustomAsset && stagedCustomAsset && <CreateCustomAsset />}
          </div>
        </ImportAsset>
      )}
      <CatalogAssetContextMenu />
      <CleanAssets
        isOpen={showCleanAssetsModal}
        assets={cleanAssets}
        isScanning={isScanning}
        selectedAssets={selectedCleanAssets}
        onClose={handleCloseCleanAssetsModal}
        onScan={handleScanAssets}
        onSelect={handleSelectCleanAsset}
        onSelectAll={handleSelectAllCleanAssets}
      />
    </div>
  );
}

export default React.memo(Assets);
